#!/bin/bash
DOMAIN_NAME=${1}
echo ${DOMAIN_NAME}
./prp/prp ./autogenerated/fond_${DOMAIN_NAME}_d.pddl ./autogenerated/fond_${DOMAIN_NAME}_p.pddl  --dump-policy 2 --optimize-final-policy 1 

python3 ./prp-scripts/translate_policy.py > ./solutionsByPRP/fond_${DOMAIN_NAME}_human_policy.out